# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений - не зарегистрированный пользователь
GET {{baseUrl}}/advertisements/
Content-Type: application/json

### получение объявлений - зарегистрированный пользователь
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 21d7c9d2cf025f85d9d84769b6d5ad23ec47e6b0

### получение объявлений - зарегистрированный пользователь
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token d614de306f5b36adf12d0034f3ffd9e09be47b34

### Удаление объявления
DELETE  {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token 974fb189d4a66ed84d54708cb6b6ff6800acc6c6


###
# создание объявления Админ
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 21d7c9d2cf025f85d9d84769b6d5ad23ec47e6b0

{
  "title": "СТол9843",
  "description": "Срочно"
}

###

# создание объявления Гость1
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 974fb189d4a66ed84d54708cb6b6ff6800acc6c6

{
  "title": "Столик67",
  "description": "Срочно"
}
###

# попытка поменять объявление админ
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token d614de306f5b36adf12d0034f3ffd9e09be47b34

{
  "status": "OPEN"
}
###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 974fb189d4a66ed84d54708cb6b6ff6800acc6c6

{
  "status": "CLOSED"
}
###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?xyz_abc=123
Content-Type: application/json

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json
###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json
###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
